from django.urls import path
from .views import (
    HomeView, ProductListView, AboutView, SafetyView, ContactView, TermsView, 
    VisionView, MissionView, FounderStoryView, CoreValuesView, WhyChooseView, 
    BrandPhilosophyView, AuraaPromiseView, AuraaManifestoView, 
    CartAddAPIView, CartRemoveAPIView, CartListAPIView,
    CouponVerifyAPIView, OrderProcessingView, AddressAddAPIView, PlaceOrderAPIView,
    OrderHistoryListView, OrderDetailView, OrderStatusListView, OrderDeleteAPIView, OrderEditView,
    TestimonialsView, StateListAPIView, CityListAPIView
)
from .views_dashboard import (
    DashboardCategoryListView, DashboardProductListView, 
    ProductToggleActiveView, DashboardOrderListView, 
    DashboardOrderDetailView, DashboardCustomerListView, AdminActiveCategoryListView,
    DashboardAnalysisView, DashboardReportCreateView, DashboardPricelistListView, PricelistToggleActiveView,
    DashboardPricelistCreateView, PricelistSaveView, DashboardPricelistDetailView, DashboardPricelistEditView,
    PricelistUpdateView, DashboardCouponListView, CouponToggleActiveView
)

urlpatterns = [
    # Admin Dashboard
    path('dashboard/', DashboardProductListView.as_view(), name='admin_dashboard'),
    path('dashboard/categories/', DashboardCategoryListView.as_view(), name='dashboard_categories'),
    path('dashboard/products/', DashboardProductListView.as_view(), name='dashboard_products'),
    path('dashboard/products/<int:pk>/toggle/', ProductToggleActiveView.as_view(), name='api_product_toggle'),
    path('dashboard/orders/', DashboardOrderListView.as_view(), name='dashboard_orders'),
    path('dashboard/order/<str:trans_no>/', DashboardOrderDetailView.as_view(), name='dashboard_order_detail'),
    path('dashboard/customers/', DashboardCustomerListView.as_view(), name='dashboard_customers'),
    path('dashboard/analysis/', DashboardAnalysisView.as_view(), name='dashboard_analysis'),
    path('dashboard/reports/create/', DashboardReportCreateView.as_view(), name='dashboard_report_create'),
    path('dashboard/pricelists/', DashboardPricelistListView.as_view(), name='dashboard_pricelists'),
    path('dashboard/pricelists/create/', DashboardPricelistCreateView.as_view(), name='dashboard_pricelist_create'),
    path('api/pricelist/save/', PricelistSaveView.as_view(), name='api_pricelist_save'),
    path('api/pricelist/<int:pk>/update/', PricelistUpdateView.as_view(), name='api_pricelist_update'),
    path('dashboard/pricelists/<int:pk>/', DashboardPricelistDetailView.as_view(), name='dashboard_pricelist_detail'),
    path('dashboard/pricelists/<int:pk>/edit/', DashboardPricelistEditView.as_view(), name='dashboard_pricelist_edit'),
    path('dashboard/pricelists/<int:pk>/toggle/', PricelistToggleActiveView.as_view(), name='api_pricelist_toggle'),
    path('dashboard/coupons/', DashboardCouponListView.as_view(), name='dashboard_coupons'),
    path('dashboard/coupons/<int:pk>/toggle/', CouponToggleActiveView.as_view(), name='api_coupon_toggle'),
    path('admin/category/', AdminActiveCategoryListView.as_view(), name='admin_active_categories'),

    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('orders/', OrderHistoryListView.as_view(), name='order_history'),
    path('order-status/', OrderStatusListView.as_view(), name='order_status'),
    path('order/<str:trans_no>/', OrderDetailView.as_view(), name='order_detail'),
    path('order/<str:trans_no>/edit/', OrderEditView.as_view(), name='order_edit'),
    path('api/order/<str:trans_no>/delete/', OrderDeleteAPIView.as_view(), name='api_order_delete'),
    path('checkout/', OrderProcessingView.as_view(), name='checkout'),
    path('api/coupon/verify/', CouponVerifyAPIView.as_view(), name='api_coupon_verify'),
    path('api/address/add/', AddressAddAPIView.as_view(), name='api_address_add'),
    path('api/order/place/', PlaceOrderAPIView.as_view(), name='api_order_place'),
    path('about/', AboutView.as_view(), name='about'),
    path('safety-tips/', SafetyView.as_view(), name='safety'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('vision/', VisionView.as_view(), name='vision'),
    path('mission/', MissionView.as_view(), name='mission'),
    path('founder-story/', FounderStoryView.as_view(), name='founder_story'),
    path('core-values/', CoreValuesView.as_view(), name='core_values'),
    path('why-choose-us/', WhyChooseView.as_view(), name='why_choose'),
    path('why choose us/', WhyChooseView.as_view()),
    path('brand-philosophy/', BrandPhilosophyView.as_view(), name='brand_philosophy'),
    path('auraa-promise/', AuraaPromiseView.as_view(), name='auraa_promise'),
    path('auraa-manifesto/', AuraaManifestoView.as_view(), name='auraa_manifesto'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('testimonials/', TestimonialsView.as_view(), name='testimonials'),
    path('api/cart/add/', CartAddAPIView.as_view(), name='api_cart_add'),
    path('api/cart/remove/', CartRemoveAPIView.as_view(), name='api_cart_remove'),
    path('api/cart/list/', CartListAPIView.as_view(), name='api_cart_list'),
    path('api/states/', StateListAPIView.as_view(), name='api_states'),
    path('api/cities/', CityListAPIView.as_view(), name='api_cities'),
]
