from django.urls import path
from .views import (
    HomeView, ProductListView, AboutView, SafetyView, ContactView, TermsView, 
    VisionView, MissionView, FounderStoryView, CoreValuesView, WhyChooseView, 
    BrandPhilosophyView, AuraaPromiseView, AuraaManifestoView, 
    CartAddAPIView, CartRemoveAPIView, CartListAPIView,
    CouponVerifyAPIView, OrderProcessingView, AddressAddAPIView, PlaceOrderAPIView,
    LoadOrderToCartView, CancelOrderEditView,
    OrderHistoryListView, OrderDetailView, OrderStatusListView, OrderDeleteAPIView,
    TestimonialsView, StateListAPIView, CityListAPIView, PrivacyView, ComplianceView,
    ProductSearchAPIView, OrderDownloadView, SpeechToTextAPIView
)
from .views_dashboard import (
    DashboardCategoryListView, DashboardProductListView, 
    ProductToggleActiveView, DashboardOrderListView, 
    DashboardOrderDetailView, DashboardOrderEstimateView, DashboardBulkOrderEstimateView, DashboardOrderDownloadView, DashboardOrderExcelDownloadView, DashboardCustomerListView, DashboardCustomerExportView, DashboardCustomerPrintView, AdminActiveCategoryListView,
    DashboardAnalysisView, DashboardReportCreateView, DashboardPricelistListView, PricelistToggleActiveView,
    DashboardPricelistCreateView, PricelistSaveView, DashboardPricelistDetailView, DashboardPricelistEditView,
    PricelistUpdateView, DashboardCouponListView, CouponToggleActiveView, CouponDetailAPIView, CouponSaveAPIView, CouponDeleteAPIView, DashboardBannerListView, BannerToggleActiveView, BannerDetailAPIView, BannerSaveAPIView, BannerDeleteAPIView,
    PricelistCheckNameAPIView, PricelistVersionDetailAPIView, PricelistListAPIView,
    CustomerToggleActiveView, CustomerDetailAPIView, CustomerUpdateAPIView, CustomerAutocompleteAPIView,
    CustomerResetPasswordAPIView, ProductAutocompleteAPIView, CategoryAutocompleteAPIView, OrderAutocompleteAPIView,
    PricelistAutocompleteAPIView, DashboardOrderUpdateStatusAPIView, DashboardOrderEditView, DashboardOrderUpdateAPIView,
    DashboardCustomerImpersonateView, ProductDetailAPIView, ProductUpdateAPIView, ProductDeleteAPIView,
    ProductCreateAPIView, ProductImageUploadAPIView, CategoryDetailAPIView, CategoryUpdateAPIView,
    CategoryCreateAPIView, CategoryDeleteAPIView, CategoryImageUploadAPIView
)

urlpatterns = [
    # Admin Dashboard
    path('dashboard/', DashboardProductListView.as_view(), name='admin_dashboard'),
    path('dashboard/categories/', DashboardCategoryListView.as_view(), name='dashboard_categories'),
    path('dashboard/products/', DashboardProductListView.as_view(), name='dashboard_products'),
    path('dashboard/products/<int:pk>/toggle/', ProductToggleActiveView.as_view(), name='api_product_toggle'),
    path('dashboard/products/<int:pk>/detail/', ProductDetailAPIView.as_view(), name='api_product_detail'),
    path('dashboard/products/<int:pk>/update/', ProductUpdateAPIView.as_view(), name='api_product_update'),
    path('dashboard/products/<int:pk>/delete/', ProductDeleteAPIView.as_view(), name='api_product_delete'),
    path('dashboard/products/create/', ProductCreateAPIView.as_view(), name='api_product_create'),
    path('dashboard/products/upload-image/', ProductImageUploadAPIView.as_view(), name='api_product_image_upload'),
    
    # Category Dashboard APIs
    path('dashboard/categories/<int:pk>/detail/', CategoryDetailAPIView.as_view(), name='api_category_detail'),
    path('dashboard/categories/<int:pk>/update/', CategoryUpdateAPIView.as_view(), name='api_category_update'),
    path('dashboard/categories/<int:pk>/delete/', CategoryDeleteAPIView.as_view(), name='api_category_delete'),
    path('dashboard/categories/create/', CategoryCreateAPIView.as_view(), name='api_category_create'),
    path('dashboard/categories/upload-image/', CategoryImageUploadAPIView.as_view(), name='api_category_image_upload'),
    path('dashboard/orders/', DashboardOrderListView.as_view(), name='dashboard_orders'),
    path('dashboard/orders/bulk-estimate/', DashboardBulkOrderEstimateView.as_view(), name='dashboard_orders_bulk_estimate'),
    path('dashboard/order/<str:trans_no>/', DashboardOrderDetailView.as_view(), name='dashboard_order_detail'),
    path('dashboard/order/<str:trans_no>/estimate/', DashboardOrderEstimateView.as_view(), name='dashboard_order_estimate'),
    path('dashboard/order/<str:trans_no>/download/', DashboardOrderDownloadView.as_view(), name='dashboard_order_download'),
    path('dashboard/order/<str:trans_no>/excel/', DashboardOrderExcelDownloadView.as_view(), name='dashboard_order_excel'),
    path('dashboard/order/<str:trans_no>/status/update/', DashboardOrderUpdateStatusAPIView.as_view(), name='api_order_status_update'),
    path('dashboard/order/<str:trans_no>/edit/', DashboardOrderEditView.as_view(), name='dashboard_order_edit'),
    path('dashboard/order/<str:trans_no>/update/', DashboardOrderUpdateAPIView.as_view(), name='api_order_update'),
    path('dashboard/customers/', DashboardCustomerListView.as_view(), name='dashboard_customers'),
    path('dashboard/customers/export/', DashboardCustomerExportView.as_view(), name='dashboard_customers_export'),
    path('dashboard/customers/print/', DashboardCustomerPrintView.as_view(), name='dashboard_customers_print'),
    path('dashboard/customers/<int:pk>/toggle/', CustomerToggleActiveView.as_view(), name='api_customer_toggle'),
    path('dashboard/customers/<int:pk>/detail/', CustomerDetailAPIView.as_view(), name='api_customer_detail'),
    path('dashboard/customers/<int:pk>/update/', CustomerUpdateAPIView.as_view(), name='api_customer_update'),
    path('dashboard/customers/autocomplete/', CustomerAutocompleteAPIView.as_view(), name='api_customer_autocomplete'),
    path('dashboard/customers/<int:pk>/reset-password/', CustomerResetPasswordAPIView.as_view(), name='api_customer_reset_password'),
    path('dashboard/customers/<int:pk>/impersonate/', DashboardCustomerImpersonateView.as_view(), name='dashboard_customer_impersonate'),
    path('dashboard/analysis/', DashboardAnalysisView.as_view(), name='dashboard_analysis'),
    path('dashboard/reports/create/', DashboardReportCreateView.as_view(), name='dashboard_report_create'),
    path('dashboard/pricelists/', DashboardPricelistListView.as_view(), name='dashboard_pricelists'),
    path('dashboard/pricelists/create/', DashboardPricelistCreateView.as_view(), name='dashboard_pricelist_create'),
    path('api/pricelist/save/', PricelistSaveView.as_view(), name='api_pricelist_save'),
    path('api/pricelist/check-name/', PricelistCheckNameAPIView.as_view(), name='api_pricelist_check_name'),
    path('api/pricelist/version-detail/', PricelistVersionDetailAPIView.as_view(), name='api_pricelist_version_detail'),
    path('api/pricelist/list/', PricelistListAPIView.as_view(), name='api_pricelist_list'),
    path('api/pricelist/<int:pk>/update/', PricelistUpdateView.as_view(), name='api_pricelist_update'),
    path('dashboard/pricelists/<int:pk>/', DashboardPricelistDetailView.as_view(), name='dashboard_pricelist_detail'),
    path('dashboard/pricelists/<int:pk>/edit/', DashboardPricelistEditView.as_view(), name='dashboard_pricelist_edit'),
    path('dashboard/pricelists/<int:pk>/toggle/', PricelistToggleActiveView.as_view(), name='api_pricelist_toggle'),
    path('dashboard/coupons/', DashboardCouponListView.as_view(), name='dashboard_coupons'),
    path('dashboard/coupons/<int:pk>/toggle/', CouponToggleActiveView.as_view(), name='api_coupon_toggle'),
    path('dashboard/coupons/<int:pk>/detail/', CouponDetailAPIView.as_view(), name='api_coupon_detail'),
    path('dashboard/coupons/save/', CouponSaveAPIView.as_view(), name='api_coupon_save'),
    path('dashboard/coupons/<int:pk>/delete/', CouponDeleteAPIView.as_view(), name='api_coupon_delete'),
    path('dashboard/banners/', DashboardBannerListView.as_view(), name='dashboard_banners'),
    path('dashboard/banners/<int:pk>/toggle/', BannerToggleActiveView.as_view(), name='api_banner_toggle'),
    path('dashboard/banners/<int:pk>/detail/', BannerDetailAPIView.as_view(), name='api_banner_detail'),
    path('dashboard/banners/save/', BannerSaveAPIView.as_view(), name='api_banner_save'),
    path('dashboard/banners/<int:pk>/delete/', BannerDeleteAPIView.as_view(), name='api_banner_delete'),
    path('admin/category/', AdminActiveCategoryListView.as_view(), name='admin_active_categories'),
    
    # Autocomplete APIs
    path('dashboard/products/autocomplete/', ProductAutocompleteAPIView.as_view(), name='api_product_autocomplete'),
    path('dashboard/categories/autocomplete/', CategoryAutocompleteAPIView.as_view(), name='api_category_autocomplete'),
    path('dashboard/orders/autocomplete/', OrderAutocompleteAPIView.as_view(), name='api_order_autocomplete'),
    path('dashboard/pricelists/autocomplete/', PricelistAutocompleteAPIView.as_view(), name='api_pricelist_autocomplete'),

    path('', HomeView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('api/product/search/', ProductSearchAPIView.as_view(), name='api_product_search'),
    path('api/speech-to-text/', SpeechToTextAPIView.as_view(), name='api_speech_to_text'),
    path('orders/', OrderHistoryListView.as_view(), name='order_history'),
    path('order-status/', OrderStatusListView.as_view(), name='order_status'),
    path('order/<str:trans_no>/', OrderDetailView.as_view(), name='order_detail'),
    path('order/<str:trans_no>/download/', OrderDownloadView.as_view(), name='order_download'),
    path('order/<str:trans_no>/edit/', LoadOrderToCartView.as_view(), name='order_edit'),
    path('order-edit/cancel/', CancelOrderEditView.as_view(), name='order_edit_cancel'),
    path('api/order/<str:trans_no>/delete/', OrderDeleteAPIView.as_view(), name='api_order_delete'),
    path('checkout/', OrderProcessingView.as_view(), name='checkout'),
    path('api/coupon/verify/', CouponVerifyAPIView.as_view(), name='api_coupon_verify'),
    path('api/address/add/', AddressAddAPIView.as_view(), name='api_address_add'),
    path('api/order/place/', PlaceOrderAPIView.as_view(), name='api_order_place'),
    path('about/', AboutView.as_view(), name='about'),
    path('safety-tips/', SafetyView.as_view(), name='safety'),
    path('terms/', TermsView.as_view(), name='terms'),
    path('privacy/', PrivacyView.as_view(), name='privacy'),
    path('compliance/', ComplianceView.as_view(), name='compliance'),
    path('vision/', VisionView.as_view(), name='vision'),
    path('mission/', MissionView.as_view(), name='mission'),
    path('founder-story/', FounderStoryView.as_view(), name='founder_story'),
    path('core-values/', CoreValuesView.as_view(), name='core_values'),
    path('why-choose-us/', WhyChooseView.as_view(), name='why_choose'),
    path('brand-philosophy/', BrandPhilosophyView.as_view(), name='brand_philosophy'),
    path('auraa-promise/', AuraaPromiseView.as_view(), name='auraa_promise'),
    path('auraa-manifesto/', AuraaManifestoView.as_view(), name='auraa_manifesto'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('testimonials/', TestimonialsView.as_view(), name='testimonials'),
    path('api/cart/add/', CartAddAPIView.as_view(), name='api_cart_add'),
    path('api/cart/remove/', CartRemoveAPIView.as_view(), name='api_cart_remove'),
    path('api/cart/list/', CartListAPIView.as_view(), name='api_cart_list'),
    path('api/states/', StateListAPIView.as_view(), name='api_states'),
    path('api/cities/', CityListAPIView.as_view(), name='api_cities'),
]
