# Generated by Django 4.2.10 on 2026-03-14 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, db_column='descr', null=True)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_role',
            },
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='tbl_users_emailId_aaf1ab_idx',
            old_name='users_email_4b85f2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='tbl_users_usernam_6b7999_idx',
            old_name='users_usernam_baeb4b_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='createdBy', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, db_column='passwordResetToken', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedDt'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='updatedBy', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='emailId', max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='tbl_users',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='roleId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
