# Generated by Django 4.2.10 on 2026-03-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0010_customer_onlinesales_onlinesalesitem'),
        ('users', '0003_user_address_user_city_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_customer',
            field=models.ForeignKey(blank=True, db_column='onlineCustomerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='crackers.customer'),
        ),
    ]
