# Generated by Django 4.2.10 on 2026-03-19 01:02

from django.db import migrations


def populate_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.get_or_create(name='Online Customer', defaults={'description': 'End users who buy products online'})
    Role.objects.get_or_create(name='Admin', defaults={'description': 'System administrators'})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_online_customer'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]
