# Generated by Django 4.2.10 on 2026-03-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260319_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, db_column='userName', max_length=150, null=True),
        ),
    ]
