# Generated by Django 4.2.10 on 2026-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='role',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='createdBy', default=1, null=True),
        ),
    ]
