# Generated by Django 5.2.13 on 2026-04-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options_alter_role_branch_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="address", null=True),
                ),
                (
                    "country_id",
                    models.IntegerField(blank=True, db_column="countryid", null=True),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_column="city", max_length=100, null=True
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        blank=True, db_column="pincode", max_length=20, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_column="isactive", default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createddt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updateddt"),
                ),
                (
                    "created_by",
                    models.IntegerField(blank=True, db_column="createdby", null=True),
                ),
                (
                    "updated_by",
                    models.IntegerField(blank=True, db_column="updatedby", null=True),
                ),
            ],
            options={
                "db_table": "tbl_users_addr",
                "managed": False,
            },
        ),
    ]
