# Generated by Django 4.2.10 on 2026-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
