# Generated by Django 4.2.10 on 2026-03-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0002_category_is_active_category_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='tbl_items_itemNam_f84e7b_idx',
            old_name='products_name_a9a494_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='tbl_items_itemCod_d622d7_idx',
            old_name='products_code_770e3a_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='createdBy', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='updatedBy', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='account_id',
            field=models.IntegerField(blank=True, db_column='accountId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.IntegerField(blank=True, db_column='createdBy', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(db_column='discount', decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_per',
            field=models.DecimalField(db_column='discountPer', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='free_qty',
            field=models.DecimalField(db_column='freeQty', decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sales',
            field=models.BooleanField(db_column='isSales', default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(db_column='itemType', default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='location_id',
            field=models.IntegerField(blank=True, db_column='locationId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_ord_qty',
            field=models.DecimalField(db_column='minOrdQty', decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_qty',
            field=models.DecimalField(db_column='openingQty', decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rate',
            field=models.DecimalField(db_column='purchaseRate', decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_no',
            field=models.IntegerField(db_column='sortNo', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_id',
            field=models.IntegerField(blank=True, db_column='taxId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_id',
            field=models.IntegerField(blank=True, db_column='unitId', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.IntegerField(blank=True, db_column='updatedBy', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDt'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, db_column='categoryImage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_column='isActive', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='categoryName', db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_column='sortNo', db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedDt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crackers.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_column='itemCode', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_column='saleDesc', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_column='isActive', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='itemName', db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, db_column='mrp', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='saleRate', db_index=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedDt'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='tbl_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tbl_items',
        ),
    ]
