# Generated by Django 4.2.10 on 2026-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0003_rename_products_name_a9a494_idx_tbl_items_itemnam_f84e7b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, db_column='descr', null=True)),
                ('conv_factor', models.DecimalField(db_column='convFactor', decimal_places=6, default=1.0, max_digits=15)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_units',
            },
        ),
    ]
