# Generated by Django 4.2.10 on 2026-03-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0004_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.AddField(
            model_name='product',
            name='outbook_item_id',
            field=models.IntegerField(db_column='outBookItemId', default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_column='SKU', max_length=50, null=True),
        ),
    ]
