# Generated by Django 4.2.10 on 2026-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0005_rename_units_unit_product_outbook_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='categoryName', db_index=True, max_length=150),
        ),
    ]
