# Generated by Django 4.2.10 on 2026-03-17 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crackers', '0007_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='unitId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crackers.unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(db_column='isActive', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
