# Generated by Django 4.2.10 on 2026-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0008_remove_product_unit_id_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(db_column='isDisabled', default=False),
        ),
    ]
