# Generated by Django 4.2.10 on 2026-03-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crackers", "0009_product_is_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=200)),
                (
                    "company",
                    models.CharField(
                        blank=True, db_column="company", max_length=200, null=True
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, db_column="contactPerson", max_length=150, null=True
                    ),
                ),
                (
                    "contact_person_no",
                    models.CharField(
                        blank=True,
                        db_column="contactPersonNo",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(blank=True, db_column="accountId", null=True),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_column="balance",
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, db_column="taxId", max_length=50, null=True
                    ),
                ),
                ("is_online", models.BooleanField(db_column="isOnline", default=True)),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="companyId", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="isActive", db_index=True, default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdDt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedDt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="createdBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_customer",
            },
        ),
        migrations.CreateModel(
            name="OnlineSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trans_no",
                    models.CharField(db_column="transNo", max_length=50, unique=True),
                ),
                ("trans_dt", models.DateTimeField(db_column="transDt")),
                (
                    "status",
                    models.CharField(
                        db_column="status", default="Pending", max_length=20
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        db_column="discount",
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "total_amt",
                    models.DecimalField(
                        db_column="totalAmt",
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "round_amt",
                    models.DecimalField(
                        db_column="roundAmt",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                    ),
                ),
                (
                    "grand_amt",
                    models.DecimalField(
                        db_column="grandAmt",
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="companyId", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="isActive", db_index=True, default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdDt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedDt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="createdBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customerId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="crackers.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Online Sales",
                "db_table": "tbl_online_sales",
            },
        ),
        migrations.CreateModel(
            name="OnlineSalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(db_column="itemName", max_length=200)),
                (
                    "item_code",
                    models.CharField(
                        blank=True, db_column="itemCode", max_length=50, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        db_column="rate", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        db_column="mrp", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        db_column="qty", decimal_places=3, max_digits=15
                    ),
                ),
                (
                    "free_qty",
                    models.DecimalField(
                        db_column="freeQty",
                        decimal_places=3,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "discount_per",
                    models.DecimalField(
                        db_column="discountPer",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amt",
                    models.DecimalField(
                        db_column="discountAmt",
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=50, null=True
                    ),
                ),
                (
                    "tax_per",
                    models.DecimalField(
                        db_column="taxPer", decimal_places=2, default=0.0, max_digits=5
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(
                        blank=True, db_column="taxName", max_length=100, null=True
                    ),
                ),
                (
                    "tax_amt",
                    models.DecimalField(
                        db_column="taxAmt", decimal_places=2, default=0.0, max_digits=15
                    ),
                ),
                (
                    "item_total",
                    models.DecimalField(
                        db_column="itemTotal", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_column="companyId", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="isActive", db_index=True, default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdDt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedDt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="createdBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_item_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "online_sales",
                    models.ForeignKey(
                        db_column="onlineSalesId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crackers.onlinesales",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="itemId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crackers.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_item_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_onlinesales_items",
            },
        ),
    ]
