# Generated by Django 4.2.10 on 2026-03-19 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crackers', '0010_customer_onlinesales_onlinesalesitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='couponName', max_length=150)),
                ('code', models.CharField(db_column='couponCode', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', db_index=True, default=True)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDT')),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_coupons',
            },
        ),
    ]
