# Generated by Django 4.2.10 on 2026-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0011_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percentage',
            field=models.DecimalField(db_column='couponPer', decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
