# Generated by Django 4.2.10 on 2026-03-19 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crackers', '0012_coupon_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(db_column='address1', max_length=255)),
                ('address2', models.CharField(blank=True, db_column='address2', max_length=255, null=True)),
                ('country_id', models.IntegerField(blank=True, db_column='countryId', null=True)),
                ('state_id', models.IntegerField(blank=True, db_column='stateId', null=True)),
                ('city_id', models.IntegerField(blank=True, db_column='cityId', null=True)),
                ('zip_code', models.CharField(db_column='zip', max_length=20)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
                ('email', models.EmailField(blank=True, db_column='emailId', max_length=255, null=True)),
                ('whatsapp_no', models.CharField(blank=True, db_column='whatsAppNo', max_length=20, null=True)),
                ('is_shipping_default', models.BooleanField(db_column='isShippingDefault', default=False)),
                ('is_active', models.BooleanField(db_column='isActive', db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addr_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crackers.customer')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addr_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'tbl_customer_addr',
            },
        ),
    ]
