# Generated by Django 4.2.10 on 2026-03-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0013_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesales',
            name='customer_address',
            field=models.ForeignKey(blank=True, db_column='customerAddrId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crackers.customeraddress'),
        ),
    ]
