# Generated by Django 4.2.10 on 2026-03-19 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crackers', '0014_onlinesales_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinesales',
            name='payment_method',
            field=models.CharField(blank=True, db_column='paymentMethod', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlinesales',
            name='payment_status',
            field=models.CharField(db_column='paymentStatus', default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinesales',
            name='status',
            field=models.CharField(db_column='status', default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=255, null=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('short_name', models.CharField(blank=True, db_column='shortName', max_length=50, null=True)),
                ('address1', models.TextField(blank=True, db_column='address1', null=True)),
                ('address2', models.TextField(blank=True, db_column='address2', null=True)),
                ('country_id', models.IntegerField(blank=True, db_column='countryId', null=True)),
                ('state_id', models.IntegerField(blank=True, db_column='stateId', null=True)),
                ('city_id', models.IntegerField(blank=True, db_column='cityId', null=True)),
                ('email_id', models.EmailField(blank=True, db_column='emailId', max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, db_column='mobileNo', max_length=20, null=True)),
                ('whatsapp_no', models.CharField(blank=True, db_column='whatsAppNo', max_length=20, null=True)),
                ('currency', models.CharField(db_column='currency', default='INR', max_length=20)),
                ('fy_start', models.DateField(blank=True, db_column='fyStart', null=True)),
                ('app_date_format', models.CharField(db_column='appDateFormat', default='DD-MM-YYYY', max_length=50)),
                ('app_color_code', models.CharField(blank=True, db_column='appColorCode', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('branch_limit', models.IntegerField(db_column='branchLimit', default=1)),
                ('user_limit', models.IntegerField(db_column='userLimit', default=5)),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'tbl_company',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=255, null=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('short_name', models.CharField(blank=True, db_column='shortName', max_length=50, null=True)),
                ('address1', models.TextField(blank=True, db_column='address1', null=True)),
                ('address2', models.TextField(blank=True, db_column='address2', null=True)),
                ('country_id', models.IntegerField(blank=True, db_column='countryId', null=True)),
                ('state_id', models.IntegerField(blank=True, db_column='stateId', null=True)),
                ('city_id', models.IntegerField(blank=True, db_column='cityId', null=True)),
                ('email_id', models.EmailField(blank=True, db_column='emailId', max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, db_column='mobileNo', max_length=20, null=True)),
                ('whatsapp_no', models.CharField(blank=True, db_column='whatsAppNo', max_length=20, null=True)),
                ('currency', models.CharField(db_column='currency', default='INR', max_length=20)),
                ('fy_start', models.DateField(blank=True, db_column='fyStart', null=True)),
                ('app_date_format', models.CharField(db_column='appDateFormat', default='DD-MM-YYYY', max_length=50)),
                ('app_color_code', models.CharField(blank=True, db_column='appColorCode', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='crackers.company')),
                ('created_by', models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'tbl_branch',
            },
        ),
    ]
