# Generated by Django 4.2.10 on 2026-03-25 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crackers', '0015_onlinesales_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('is_active', models.IntegerField(db_column='isActive', default=1)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
            ],
            options={
                'db_table': 'tbl_city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
            ],
            options={
                'db_table': 'tbl_country',
            },
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(db_column='listName', max_length=150)),
                ('list_desc', models.TextField(blank=True, db_column='listDesc', null=True)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('is_active', models.IntegerField(db_column='isActive', default=1)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_pricelist',
            },
        ),
        migrations.CreateModel(
            name='PricelistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=50, null=True)),
                ('purchase_rate', models.DecimalField(db_column='purchaseRate', decimal_places=2, default=0.0, max_digits=15)),
                ('purchase_rate_inc', models.DecimalField(db_column='purchaseRateInc', decimal_places=2, default=0.0, max_digits=15)),
                ('selling_price', models.DecimalField(db_column='sellingPrice', decimal_places=2, default=0.0, max_digits=15)),
                ('customer_sp', models.DecimalField(db_column='customerSp', decimal_places=2, default=0.0, max_digits=15)),
                ('shown_values', models.DecimalField(db_column='shownValues', decimal_places=2, default=0.0, max_digits=15)),
                ('shown_value_disc', models.DecimalField(db_column='shownValueDisc', decimal_places=2, default=0.0, max_digits=5)),
                ('sales_cost', models.DecimalField(db_column='salesCost', decimal_places=2, default=0.0, max_digits=15)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('is_active', models.IntegerField(db_column='isActive', default=1)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
                ('pricelist', models.ForeignKey(db_column='pricelistId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crackers.pricelist')),
            ],
            options={
                'db_table': 'tbl_pricelist_items',
            },
        ),
        migrations.CreateModel(
            name='SerialNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_column='tableName', max_length=100)),
                ('prefix_no', models.CharField(blank=True, db_column='prefixNo', max_length=20, null=True)),
                ('next_no', models.IntegerField(db_column='nextNo', default=1)),
                ('sequence_no', models.IntegerField(db_column='sequenceNo', default=1)),
                ('suffix_no', models.CharField(blank=True, db_column='suffixNo', max_length=20, null=True)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_serialno',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('country', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.CASCADE, to='crackers.country')),
            ],
            options={
                'db_table': 'tbl_state',
            },
        ),
        migrations.CreateModel(
            name='WebsiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(db_column='websiteName', max_length=255)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
            ],
            options={
                'db_table': 'tbl_websitelist',
            },
        ),
        migrations.AlterModelOptions(
            name='onlinesales',
            options={'managed': False, 'verbose_name_plural': 'Online Sales'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outbook_item_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='coupon',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='website_id',
            field=models.IntegerField(blank=True, db_column='websiteId', default=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website_id',
            field=models.IntegerField(blank=True, db_column='websiteId', default=2, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city_name',
            field=models.CharField(blank=True, db_column='cityName', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='pincode',
            field=models.CharField(db_column='pincode', default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinesalesitem',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='whatsapp_no',
            field=models.CharField(blank=True, db_column='whatsappNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_no',
            field=models.CharField(blank=True, db_column='whatsappNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdDt'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedDt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addr_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='whatsapp_no',
            field=models.CharField(blank=True, db_column='whatsappNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onlinesalesitem',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='onlinesalesitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_item_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, db_column='itemImage', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_disabled',
            field=models.IntegerField(db_column='isDisabled', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sales',
            field=models.IntegerField(db_column='isSales', default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='branch_id',
            field=models.IntegerField(blank=True, db_column='branchId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='company_id',
            field=models.IntegerField(blank=True, db_column='companyId', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.CASCADE, to='crackers.product'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, to='crackers.state'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(db_column='itemId', on_delete=django.db.models.deletion.CASCADE, to='crackers.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, db_column='cityId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.city'),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(blank=True, db_column='countryId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.country'),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(blank=True, db_column='stateId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.state'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, db_column='cityId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.city'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, db_column='countryId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, db_column='stateId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.state'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.ForeignKey(blank=True, db_column='countryId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.country'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.ForeignKey(blank=True, db_column='stateId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crackers.state'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
