# Generated by Django 4.2.10 on 2026-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0016_cart_city_country_pricelist_pricelistitem_serialno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address2',
            field=models.CharField(db_column='address2', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city_name',
            field=models.CharField(db_column='cityName', default='', max_length=100),
            preserve_default=False,
        ),
    ]
