# Generated by Django 4.2.10 on 2026-03-30 08:09

from django.db import migrations


def cleanup_names(apps, schema_editor):
    Product = apps.get_model('crackers', 'Product')
    Category = apps.get_model('crackers', 'Category')
    OnlineSalesItem = apps.get_model('crackers', 'OnlineSalesItem')

    for p in Product.objects.filter(name__icontains='\\'):
        p.name = p.name.replace('\\', '')
        p.save()

    for c in Category.objects.filter(name__icontains='\\'):
        c.name = c.name.replace('\\', '')
        c.save()

    for i in OnlineSalesItem.objects.filter(item_name__icontains='\\'):
        i.item_name = i.item_name.replace('\\', '')
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0017_alter_customeraddress_address2_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_names),
    ]
