# Generated by Django 4.2.10 on 2026-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0018_cleanup_product_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='pl_version',
            field=models.CharField(db_column='plVersion', default='1.0', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='tbl_items_saleRat_cdd488_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='tbl_items_created_00271d_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('list_name', 'pl_version'), name='unique_pricelist_version'),
        ),
    ]
