# Generated by Django 5.2.13 on 2026-04-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crackers", "0019_pricelist_pl_version_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="pricelistitem",
            options={"ordering": ["product__sort_no", "product__name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort_no", "name"]},
        ),
    ]
