# Generated by Django 4.2.10 on 2026-04-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0020_alter_category_options_alter_pricelistitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='reviewerName', max_length=200)),
                ('profile_image', models.URLField(blank=True, db_column='reviewerImage', max_length=1000, null=True)),
                ('rating', models.IntegerField(db_column='rating', default=5)),
                ('text', models.TextField(db_column='reviewText')),
                ('review_date', models.CharField(db_column='reviewDate', max_length=100)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
            ],
            options={
                'db_table': 'tbl_testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
