# Generated by Django 4.2.10 on 2026-05-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0021_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
                ('website_id', models.IntegerField(blank=True, db_column='websiteId', default=2, null=True)),
                ('is_show', models.BooleanField(db_column='isShow', default=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('company_id', models.IntegerField(blank=True, db_column='companyId', default=1, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='branchId', default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdDt')),
                ('created_by', models.IntegerField(blank=True, db_column='createdBy', default=1, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedDt')),
                ('updated_by', models.IntegerField(blank=True, db_column='updatedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_banner',
            },
        ),
    ]
