# Generated by Django 5.2.13 on 2026-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crackers", "0022_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="address1",
            field=models.CharField(
                blank=True, db_column="address1", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="address2",
            field=models.CharField(
                blank=True, db_column="address2", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="city_name",
            field=models.CharField(
                blank=True, db_column="cityName", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="pincode",
            field=models.CharField(
                blank=True, db_column="pincode", max_length=20, null=True
            ),
        ),
    ]
